# Generated by Django 2.1 on 2018-08-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=70)),
                ('artist_age', models.CharField(max_length=20)),
                ('artist_photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(max_length=100)),
                ('artwork_photo_url', models.TextField()),
                ('artwork_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='showtime.Artist')),
            ],
        ),
    ]
