# Generated by Django 2.1 on 2018-08-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_name',
            new_name='show_title',
        ),
    ]
