# Generated by Django 2.1 on 2018-08-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0002_auto_20180817_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='actor',
            new_name='show_actor',
        ),
    ]
